version: '3.9'

services:
  hydra:
    image: oryd/hydra:v2.2
    container_name: ory-hydra
    ports:
      - "4444:4444"
      - "4445:4445"
    env_file:
      - .env
    environment:
      - DSN=${HYDRA_DSN}
      - URLS_SELF_ISSUER=${HYDRA_URLS_SELF_ISSUER}
      - URLS_CONSENT=${HYDRA_URLS_CONSENT}
      - URLS_LOGIN=${HYDRA_URLS_LOGIN}
      - SECRETS_SYSTEM=${HYDRA_SECRETS_SYSTEM}
    command: serve all --dev
    networks:
      - ory-network

  ory-kratos:
    image: oryd/kratos:v1.1
    container_name: ory-kratos
    ports:
      - '4433:4433'
      - '4434:4434'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DSN=${KRATOS_DSN}
      - LOG_LEVEL=${KRATOS_LOG_LEVEL}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - CSRF_COOKIE_NAME=${KRATOS_CSRF_COOKIE_NAME}
      - CSRF_COOKIE_SECRET=${KRATOS_CSRF_COOKIE_SECRET}
      - KRATOS_CIPHER_SECRET=${KRATOS_CIPHER_SECRET}
      - SERVE_PUBLIC_BASE_URL=${KRATOS_SERVE_PUBLIC_BASE_URL}
      - SERVE_ADMIN_BASE_URL=${KRATOS_SERVE_ADMIN_BASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    command: serve -c /etc/config/kratos.yml --watch-courier
    volumes:
      - ./config:/etc/config
    networks:
      - ory-network

networks:
  ory-network:
    driver: bridge
