version: '3.9'

services:
  hydra:
    image: oryd/hydra:v2.2
    container_name: ory-hydra
    ports:
      - "4444:4444"
      - "4445:4445"
    env_file:
      - .env
    environment:
      - DSN=${HYDRA_DSN}
      - URLS_SELF_ISSUER=${HYDRA_URLS_SELF_ISSUER}
      - URLS_CONSENT=${HYDRA_URLS_CONSENT}
      - URLS_LOGIN=${HYDRA_URLS_LOGIN}
      - SECRETS_SYSTEM=${HYDRA_SECRETS_SYSTEM}
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=https://login.daybook.com,https://app.daybook.com,
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=Authorization,Content-Type,Accept
      - CORS_ALLOW_CREDENTIALS=true
    command: serve all --dev
    networks:
      - ory-network

  ory-kratos:
    image: oryd/kratos:v1.3.1
    container_name: ory-kratos
    ports:
      - '4433:4433'
      - '4434:4434'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SERVE_PUBLIC_BASE_URL=${KRATOS_URL}
      - DSN=${KRATOS_DSN}
      - LOG_LEVEL=${KRATOS_LOG_LEVEL}
      - SECRETS_COOKIE=${KRATOS_CSRF_COOKIE_SECRET}
      - SECRETS_CIPHER=${KRATOS_CIPHER_SECRET}
      - SERVE_PUBLIC_BASE_URL=${KRATOS_SERVE_PUBLIC_BASE_URL}
      - SERVE_ADMIN_BASE_URL=${KRATOS_SERVE_ADMIN_BASE_URL}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS=${KRATOS_OIDC_PROVIDERS}
    command: serve -c /etc/config/kratos.yml --watch-courier
    volumes:
      - ./config:/etc/config
    networks:
      - ory-network

networks:
  ory-network:
    driver: bridge
