version: '3.9'

services:
  kratos:
    image: oryd/kratos:v1.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=
      - LOG_LEVEL=trace
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - SERVE_PUBLIC_BASE_URL=http://127.0.0.1:4433/
      - SERVE_ADMIN_BASE_URL=http://127.0.0.1:4434/
    command: serve -c /etc/config/kratos.yml --watch-courier
    volumes:
      - ./config:/etc/config
    networks:
      - my-network

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    ports:
      - "4455:4455"
    environment:
      - PORT=4455
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
    networks:
      - my-network
    restart: on-failure
    depends_on:
      - kratos

networks:
  my-network:
