serve:
  public:
    base_url: replaced from env
    cors:
      enabled: true
      allowed_origins:
        - https://auth-local.daybook.cloud
        - https://app-local.daybook.cloud
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Content-Type
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
  admin:
    base_url: http://kratos:4434/

cookies:
  same_site: None
  domain: .daybook.cloud


selfservice:
  default_browser_return_url: https://auth-local.daybook.cloud/handle-login-return
  allowed_return_urls:
    - https://auth-local.daybook.cloud/handle-login-return

  methods:
    password:
      enabled: false
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      enabled: true
      config: {}

  flows:
    error:
      ui_url: https://auth-local.daybook.cloud/error

    settings:
      ui_url: https://auth-local.daybook.cloud/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://auth-local.daybook.cloud/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://auth-local.daybook.cloud/verification
      use: code
      after:
        default_browser_return_url: https://auth-local.daybook.cloud/handle-login-return

    logout:
      after:
        default_browser_return_url: https://auth-local.daybook.cloud/login

    login:
      ui_url: https://auth-local.daybook.cloud/login
      lifespan: 10m

    registration:
      enabled: true
      lifespan: 10m
      ui_url: https://auth-local.daybook.cloud/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: repalced from env
  format: text
  leak_sensitive_values: true
  
secrets:
  cookie:
    - replaced from env
  cipher:
    - replaced from env

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

feature_flags:
  use_continue_with_transitions: true
