dsn: ${KRATOS_DSN}

serve:
  public:
    base_url: ${KRATOS_SERVE_PUBLIC_BASE_URL}
    cors:
      enabled: true
      allowed_origins: [${CORS_ALLOWED_ORIGINS}]
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Content-Type
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
  admin:
    base_url: ${KRATOS_ADMIN_URL}

cookies:
  same_site: None
  domain: ${KRATOS_COOKIES_DOMAIN}

selfservice:
  default_browser_return_url: ${AUTH_URL}/handle-login-return
  allowed_return_urls:
    - ${AUTH_URL}/handle-login-return
    - ${KRATOS_URLS_LOGOUT}

  methods:
    password:
      enabled: false
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            mapper_url: file:///etc/config/kratos/oidc.google.mapper.jsonnet
            client_id: ${GOOGLE_CLIENT_ID}
            client_secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            auth_url: https://accounts.google.com/o/oauth2/v2/auth
            token_url: https://www.googleapis.com/oauth2/v4/token
            issuer_url: https://accounts.google.com

  flows:
    error:
      ui_url: ${AUTH_URL}/error

    settings:
      ui_url: ${AUTH_URL}/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: ${AUTH_URL}/recovery
      use: code

    verification:
      enabled: true
      ui_url: ${AUTH_URL}/verification
      use: code
      after:
        default_browser_return_url: ${AUTH_URL}/handle-login-return

    logout:
      after:
        default_browser_return_url: ${KRATOS_URLS_LOGOUT}

    login:
      ui_url: ${AUTH_URL}/login
      lifespan: 10m

    registration:
      enabled: true
      lifespan: 10m
      ui_url: ${AUTH_URL}/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: ${KRATOS_LOG_LEVEL}
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - ${KRATOS_CSRF_COOKIE_SECRET}
  cipher:
    - ${KRATOS_CIPHER_SECRET}

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

feature_flags:
  use_continue_with_transitions: true
