# admin-backend API -> :4100
server {
  listen 443 ssl;
  server_name admin-api-local.idnest.cloud;

  ssl_certificate     /opt/homebrew/etc/nginx/ssl/local.idnest.cloud.pem;
  ssl_certificate_key /opt/homebrew/etc/nginx/ssl/local.idnest.cloud-key.pem;

  location / {
    proxy_pass http://localhost:4100;
    proxy_set_header Host              $host;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
  }
}

server {
  listen 80;
  server_name admin-api-local.idnest.cloud;
  return 301 https://$host$request_uri;
}
